/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_poo2;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class FormsMissaoMestre extends javax.swing.JFrame {

    /**
     * Creates new form FormsMissao
     */
    public FormsMissaoMestre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cxObjetivo = new javax.swing.JTextField();
        rtRecompensa = new javax.swing.JLabel();
        cxRecompensa = new javax.swing.JTextField();
        btCadMissao = new javax.swing.JButton();
        btAltMissao = new javax.swing.JButton();
        btConsMissao = new javax.swing.JButton();
        rtTitulo = new javax.swing.JLabel();
        btExcMissao = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        rtNome = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        cxNome = new javax.swing.JTextField();
        rtObjetivo = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        rtSubtitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtRecompensa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtRecompensa.setText("Recompensa:");

        btCadMissao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btCadMissao.setText("Cadastrar");
        btCadMissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadMissaoActionPerformed(evt);
            }
        });

        btAltMissao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btAltMissao.setText("Alterar");
        btAltMissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltMissaoActionPerformed(evt);
            }
        });

        btConsMissao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btConsMissao.setText("Consultar");
        btConsMissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsMissaoActionPerformed(evt);
            }
        });

        rtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rtTitulo.setText("Missão");

        btExcMissao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btExcMissao.setText("Excluir");
        btExcMissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcMissaoActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        rtNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtNome.setText("Nome:");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        cxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeActionPerformed(evt);
            }
        });

        rtObjetivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtObjetivo.setText("Objetivo:");

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        rtSubtitulo.setText("(consultas, alterações e exclusões por nome da Missão)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(rtRecompensa)
                                .addGap(18, 18, 18)
                                .addComponent(cxRecompensa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtObjetivo)
                                .addGap(18, 18, 18)
                                .addComponent(cxObjetivo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtNome)
                                .addGap(18, 18, 18)
                                .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(rtSubtitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 307, Short.MAX_VALUE)
                                .addComponent(rtTitulo)
                                .addGap(109, 109, 109))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCadMissao)
                                .addGap(18, 18, 18)
                                .addComponent(btAltMissao)
                                .addGap(18, 18, 18)
                                .addComponent(btConsMissao)
                                .addGap(18, 18, 18)
                                .addComponent(btExcMissao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(btLimpar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtSubtitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtObjetivo)
                    .addComponent(cxObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtRecompensa)
                    .addComponent(cxRecompensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadMissao)
                    .addComponent(btAltMissao)
                    .addComponent(btConsMissao)
                    .addComponent(btExcMissao)
                    .addComponent(btLimpar)
                    .addComponent(btSair)
                    .addComponent(btVoltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void cxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        voltar();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btCadMissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadMissaoActionPerformed
        Missao missao = new Missao(0,"","","");

        try {
            String t1 = cxNome.getText();
            String t2 = cxObjetivo.getText();
            String t3 = cxRecompensa.getText();
      
            missao.setNome(t1);
            missao.setObjetivo(t2);
            missao.setRecompensa(t3);

            if(t1.isEmpty() || t2.isEmpty() || t3.isEmpty()){
                throw new NullPointerException("Um ou mais campos estão vazios.");
            }
        }catch (IllegalArgumentException | NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
            return;
        }
        
        MissaoDAO dao = new MissaoDAO();
        dao.inserir(missao);
// TODO add your handling code here:
    }//GEN-LAST:event_btCadMissaoActionPerformed

    private void btExcMissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcMissaoActionPerformed
        String nome = cxNome.getText();
        MissaoDAO dao = new MissaoDAO();
        dao.excluir(nome);        // TODO add your handling code here:
    }//GEN-LAST:event_btExcMissaoActionPerformed

    private void btConsMissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsMissaoActionPerformed
        String nome = cxNome.getText();
        MissaoDAO dao = new MissaoDAO();
        Missao missao = dao.consultar(nome);
        if (missao != null){
            cxObjetivo.setText(missao.getObjetivo());
            cxRecompensa.setText(missao.getRecompensa());
        } else {
            JOptionPane.showMessageDialog(null,"Missão não encontrada", "Aviso", JOptionPane.WARNING_MESSAGE);
            cxObjetivo.setText("");
            cxNome.setText("");
            cxRecompensa.setText("");
           }
    }//GEN-LAST:event_btConsMissaoActionPerformed
        MissaoDAO dao = new MissaoDAO();      
        private Missao missao;
    private void btAltMissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltMissaoActionPerformed
        if (missao == null) {
            String nome = cxNome.getText();
            missao = dao.consultar(nome);

            if (missao != null) {
                cxObjetivo.setText(missao.getObjetivo());
                cxRecompensa.setText(missao.getRecompensa());
            } else {
                JOptionPane.showMessageDialog(null, "Missao não encontrada", "Aviso", JOptionPane.WARNING_MESSAGE);
                limpar();
            }
            
        }else {
                    if (!missao.getNome().equals(cxNome.getText())) {
                        JOptionPane.showMessageDialog(null, "O nome da missão não pode ser alterada", "Aviso", JOptionPane.WARNING_MESSAGE);
                        cxNome.setText(missao.getNome()); // Reseta o nome para o original
                    }else {
                        missao.setObjetivo(cxObjetivo.getText());
                        missao.setRecompensa(cxRecompensa.getText());
                        dao.atualizar(missao);
                        JOptionPane.showMessageDialog(null, "Missão atualizada com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                        resetForm();
                }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btAltMissaoActionPerformed

    /**
     * @param args the command line arguments
     */

    public void voltar(){
        FrameMestre frameMestre = new FrameMestre();
        frameMestre.setLocationRelativeTo(frameMestre);
        frameMestre.setVisible(true);
        dispose();
    }
    
    public void limpar(){
        cxNome.setText("");
        cxObjetivo.setText("");
        cxRecompensa.setText("");
    }       
     
    public void sair(){
            int respSair = JOptionPane.showConfirmDialog(
                        null,
                        "Deseja sair?",
                        "Saida",
                        JOptionPane.YES_NO_OPTION
                );
        if(respSair == 0){
            //System.exit(0);
            dispose();
        }
    }
    
    private void resetForm() {
        missao = null;
        cxNome.setText("");
        limpar();
    }          
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormsMissaoMestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormsMissaoMestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormsMissaoMestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormsMissaoMestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormsMissaoMestre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltMissao;
    private javax.swing.JButton btCadMissao;
    private javax.swing.JButton btConsMissao;
    private javax.swing.JButton btExcMissao;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxObjetivo;
    private javax.swing.JTextField cxRecompensa;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtObjetivo;
    private javax.swing.JLabel rtRecompensa;
    private javax.swing.JLabel rtSubtitulo;
    private javax.swing.JLabel rtTitulo;
    // End of variables declaration//GEN-END:variables
}
