/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_poo2;

/**
 *
 * @author bruno
 */
public class FrameMestre extends javax.swing.JFrame {

    /**
     * Creates new form FrameMestre
     */
    public FrameMestre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoPrincipalMestre = new javax.swing.JLabel();
        textoPersonagem = new javax.swing.JLabel();
        textoEquipamento = new javax.swing.JLabel();
        textoInimigo = new javax.swing.JLabel();
        textoHabilidade = new javax.swing.JLabel();
        textoMissao = new javax.swing.JLabel();
        botaoConsultarPersonagem = new javax.swing.JButton();
        botaoCadastrarEquipamento = new javax.swing.JButton();
        botaoCadastrarInimigo = new javax.swing.JButton();
        botaoCadastrarHabilidade = new javax.swing.JButton();
        botaoCadastrarMissao = new javax.swing.JButton();
        botaoConsultarEquipamento = new javax.swing.JButton();
        botaoConsultarInimigo = new javax.swing.JButton();
        botaoConsultarHabilidade = new javax.swing.JButton();
        botaoConsultarMissao = new javax.swing.JButton();
        botaoAlterarPersonagem = new javax.swing.JButton();
        botaoAlterarEquipamento = new javax.swing.JButton();
        botaoAlterarInimigo = new javax.swing.JButton();
        botaoAlterarHabilidade = new javax.swing.JButton();
        botaoAlterarMissao = new javax.swing.JButton();
        botaoExcluirPersonagem = new javax.swing.JButton();
        botaoExcluirEquipamento = new javax.swing.JButton();
        botaoExcluirInimigo = new javax.swing.JButton();
        botaoExcluirHabilidade = new javax.swing.JButton();
        botaoExcluirMissao = new javax.swing.JButton();
        botaoVoltarMestre = new javax.swing.JButton();
        botaoCalcNivel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoPrincipalMestre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textoPrincipalMestre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPrincipalMestre.setText("Olá Mestre! Por favor, escolha a opção relativa à sua busca:");
        textoPrincipalMestre.setToolTipText("");
        textoPrincipalMestre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textoPersonagem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoPersonagem.setText("Personagem");

        textoEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoEquipamento.setText("Equipamento");

        textoInimigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoInimigo.setText("Inimigo");

        textoHabilidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoHabilidade.setText("Habilidade");

        textoMissao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoMissao.setText("Missão");

        botaoConsultarPersonagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoConsultarPersonagem.setText("Consultar");
        botaoConsultarPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarPersonagemActionPerformed(evt);
            }
        });

        botaoCadastrarEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoCadastrarEquipamento.setText("Cadastrar");
        botaoCadastrarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarEquipamentoActionPerformed(evt);
            }
        });

        botaoCadastrarInimigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoCadastrarInimigo.setText("Cadastrar");
        botaoCadastrarInimigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarInimigoActionPerformed(evt);
            }
        });

        botaoCadastrarHabilidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoCadastrarHabilidade.setText("Cadastrar");
        botaoCadastrarHabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarHabilidadeActionPerformed(evt);
            }
        });

        botaoCadastrarMissao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoCadastrarMissao.setText("Cadastrar");
        botaoCadastrarMissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarMissaoActionPerformed(evt);
            }
        });

        botaoConsultarEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoConsultarEquipamento.setText("Consultar");
        botaoConsultarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarEquipamentoActionPerformed(evt);
            }
        });

        botaoConsultarInimigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoConsultarInimigo.setText("Consultar");
        botaoConsultarInimigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarInimigoActionPerformed(evt);
            }
        });

        botaoConsultarHabilidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoConsultarHabilidade.setText("Consultar");
        botaoConsultarHabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarHabilidadeActionPerformed(evt);
            }
        });

        botaoConsultarMissao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoConsultarMissao.setText("Consultar");
        botaoConsultarMissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarMissaoActionPerformed(evt);
            }
        });

        botaoAlterarPersonagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoAlterarPersonagem.setText("Alterar");

        botaoAlterarEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoAlterarEquipamento.setText("Alterar");

        botaoAlterarInimigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoAlterarInimigo.setText("Alterar");

        botaoAlterarHabilidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoAlterarHabilidade.setText("Alterar");

        botaoAlterarMissao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoAlterarMissao.setText("Alterar");

        botaoExcluirPersonagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoExcluirPersonagem.setText("Excluir");

        botaoExcluirEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoExcluirEquipamento.setText("Excluir");

        botaoExcluirInimigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoExcluirInimigo.setText("Excluir");

        botaoExcluirHabilidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoExcluirHabilidade.setText("Excluir");

        botaoExcluirMissao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoExcluirMissao.setText("Excluir");

        botaoVoltarMestre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoVoltarMestre.setText("Voltar para a tela principal");
        botaoVoltarMestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarMestreActionPerformed(evt);
            }
        });

        botaoCalcNivel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoCalcNivel.setText("Calcular Nível");
        botaoCalcNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalcNivelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoPrincipalMestre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoVoltarMestre)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoPersonagem)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(botaoExcluirPersonagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoAlterarPersonagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoConsultarPersonagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoCalcNivel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoEquipamento)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botaoExcluirEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botaoCadastrarEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(17, 17, 17)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(textoInimigo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(botaoConsultarInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botaoCadastrarHabilidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botaoAlterarInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botaoExcluirInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(50, 50, 50))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(botaoAlterarEquipamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoConsultarEquipamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(194, 194, 194)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoHabilidade)
                            .addComponent(botaoCadastrarInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoConsultarHabilidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoAlterarHabilidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoExcluirHabilidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoConsultarMissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoMissao)
                            .addComponent(botaoCadastrarMissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoAlterarMissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoExcluirMissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoPrincipalMestre)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPersonagem)
                    .addComponent(textoEquipamento)
                    .addComponent(textoInimigo)
                    .addComponent(textoHabilidade)
                    .addComponent(textoMissao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrarEquipamento)
                    .addComponent(botaoCadastrarInimigo)
                    .addComponent(botaoCadastrarMissao)
                    .addComponent(botaoCadastrarHabilidade)
                    .addComponent(botaoCalcNivel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConsultarEquipamento)
                    .addComponent(botaoConsultarInimigo)
                    .addComponent(botaoConsultarHabilidade)
                    .addComponent(botaoConsultarMissao)
                    .addComponent(botaoConsultarPersonagem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAlterarEquipamento)
                    .addComponent(botaoAlterarInimigo)
                    .addComponent(botaoAlterarHabilidade)
                    .addComponent(botaoAlterarMissao)
                    .addComponent(botaoAlterarPersonagem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExcluirEquipamento)
                    .addComponent(botaoExcluirInimigo)
                    .addComponent(botaoExcluirHabilidade)
                    .addComponent(botaoExcluirMissao)
                    .addComponent(botaoExcluirPersonagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(botaoVoltarMestre)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoConsultarPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarPersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoConsultarPersonagemActionPerformed

    private void botaoCadastrarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarEquipamentoActionPerformed

    private void botaoCadastrarInimigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarInimigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarInimigoActionPerformed

    private void botaoCadastrarHabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarHabilidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarHabilidadeActionPerformed

    private void botaoCadastrarMissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarMissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarMissaoActionPerformed

    private void botaoConsultarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoConsultarEquipamentoActionPerformed

    private void botaoConsultarInimigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarInimigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoConsultarInimigoActionPerformed

    private void botaoConsultarHabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarHabilidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoConsultarHabilidadeActionPerformed

    private void botaoConsultarMissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarMissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoConsultarMissaoActionPerformed

    private void botaoVoltarMestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarMestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoVoltarMestreActionPerformed

    private void botaoCalcNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCalcNivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMestre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterarEquipamento;
    private javax.swing.JButton botaoAlterarHabilidade;
    private javax.swing.JButton botaoAlterarInimigo;
    private javax.swing.JButton botaoAlterarMissao;
    private javax.swing.JButton botaoAlterarPersonagem;
    private javax.swing.JButton botaoCadastrarEquipamento;
    private javax.swing.JButton botaoCadastrarHabilidade;
    private javax.swing.JButton botaoCadastrarInimigo;
    private javax.swing.JButton botaoCadastrarMissao;
    private javax.swing.JButton botaoCalcNivel;
    private javax.swing.JButton botaoConsultarEquipamento;
    private javax.swing.JButton botaoConsultarHabilidade;
    private javax.swing.JButton botaoConsultarInimigo;
    private javax.swing.JButton botaoConsultarMissao;
    private javax.swing.JButton botaoConsultarPersonagem;
    private javax.swing.JButton botaoExcluirEquipamento;
    private javax.swing.JButton botaoExcluirHabilidade;
    private javax.swing.JButton botaoExcluirInimigo;
    private javax.swing.JButton botaoExcluirMissao;
    private javax.swing.JButton botaoExcluirPersonagem;
    private javax.swing.JButton botaoVoltarMestre;
    private javax.swing.JLabel textoEquipamento;
    private javax.swing.JLabel textoHabilidade;
    private javax.swing.JLabel textoInimigo;
    private javax.swing.JLabel textoMissao;
    private javax.swing.JLabel textoPersonagem;
    private javax.swing.JLabel textoPrincipalMestre;
    // End of variables declaration//GEN-END:variables
}
