/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_poo2;

/**
 *
 * @author Fernando
 */
public class FrameJogador extends javax.swing.JFrame {

    /**
     * Creates new form FrameJogador
     */
    public FrameJogador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoPrincipalJogador = new javax.swing.JLabel();
        textoPersonagem = new javax.swing.JLabel();
        textoEquipamento = new javax.swing.JLabel();
        textoInimigo = new javax.swing.JLabel();
        textoHabilidade = new javax.swing.JLabel();
        textoMissao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoPrincipalJogador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textoPrincipalJogador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPrincipalJogador.setText("Olá Jogador! Por favor, escolha a opção relativa à sua busca:");
        textoPrincipalJogador.setToolTipText("");
        textoPrincipalJogador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textoPersonagem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoPersonagem.setText("Personagem");

        textoEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoEquipamento.setText("Equipamento");

        textoInimigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoInimigo.setText("Inimigo");

        textoHabilidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoHabilidade.setText("Habilidade");

        textoMissao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoMissao.setText("Missão");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoPersonagem)
                        .addGap(63, 63, 63)
                        .addComponent(textoEquipamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoInimigo)
                        .addGap(61, 61, 61)
                        .addComponent(textoHabilidade)
                        .addGap(51, 51, 51)
                        .addComponent(textoMissao))
                    .addComponent(textoPrincipalJogador))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoPrincipalJogador)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPersonagem)
                    .addComponent(textoEquipamento)
                    .addComponent(textoInimigo)
                    .addComponent(textoHabilidade)
                    .addComponent(textoMissao))
                .addContainerGap(435, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameJogador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel textoEquipamento;
    private javax.swing.JLabel textoHabilidade;
    private javax.swing.JLabel textoInimigo;
    private javax.swing.JLabel textoMissao;
    private javax.swing.JLabel textoPersonagem;
    private javax.swing.JLabel textoPrincipalJogador;
    // End of variables declaration//GEN-END:variables
}
