/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_poo2;

/**
 *
 * @author Fernando
 */
public class FrameJogador extends javax.swing.JFrame {

    /**
     * Creates new form FrameJogador
     */
    public FrameJogador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoPrincipalJogador = new javax.swing.JLabel();
        textoPersonagem = new javax.swing.JLabel();
        textoEquipamento = new javax.swing.JLabel();
        textoInimigo = new javax.swing.JLabel();
        textoHabilidade = new javax.swing.JLabel();
        textoMissao = new javax.swing.JLabel();
        cadastrarPersonagem = new javax.swing.JButton();
        consultarPersonagem = new javax.swing.JButton();
        consultarEquipamento = new javax.swing.JButton();
        consultarInimigo = new javax.swing.JButton();
        consultarHabilidade = new javax.swing.JButton();
        consultarMissao = new javax.swing.JButton();
        botaoVoltarPersonagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Página do Jogador");

        textoPrincipalJogador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textoPrincipalJogador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPrincipalJogador.setText("Olá Jogador! Por favor, escolha a opção relativa à sua busca:");
        textoPrincipalJogador.setToolTipText("");
        textoPrincipalJogador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textoPersonagem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoPersonagem.setText("Personagem");

        textoEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoEquipamento.setText("Equipamento");

        textoInimigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoInimigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoInimigo.setText("Inimigo");

        textoHabilidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoHabilidade.setText("Habilidade");

        textoMissao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoMissao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoMissao.setText("Missão");

        cadastrarPersonagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastrarPersonagem.setText("Cadastrar");

        consultarPersonagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultarPersonagem.setText("Consultar");
        consultarPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarPersonagemActionPerformed(evt);
            }
        });

        consultarEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultarEquipamento.setText("Consultar");

        consultarInimigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultarInimigo.setText("Consultar");

        consultarHabilidade.setText("Consultar");
        consultarHabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarHabilidadeActionPerformed(evt);
            }
        });

        consultarMissao.setText("Consultar");

        botaoVoltarPersonagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoVoltarPersonagem.setText("Voltar para a tela principal");
        botaoVoltarPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarPersonagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoPrincipalJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoVoltarPersonagem)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(consultarPersonagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cadastrarPersonagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoPersonagem))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(consultarEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoEquipamento))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(consultarInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoHabilidade)
                                    .addComponent(consultarHabilidade))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(consultarMissao, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoMissao, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoPrincipalJogador)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPersonagem)
                    .addComponent(textoEquipamento)
                    .addComponent(textoInimigo)
                    .addComponent(textoHabilidade)
                    .addComponent(textoMissao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarPersonagem)
                    .addComponent(consultarEquipamento)
                    .addComponent(consultarInimigo)
                    .addComponent(consultarHabilidade)
                    .addComponent(consultarMissao))
                .addGap(18, 18, 18)
                .addComponent(consultarPersonagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(botaoVoltarPersonagem)
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarPersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarPersonagemActionPerformed

    private void consultarHabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarHabilidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarHabilidadeActionPerformed

    private void botaoVoltarPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarPersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoVoltarPersonagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameJogador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltarPersonagem;
    private javax.swing.JButton cadastrarPersonagem;
    private javax.swing.JButton consultarEquipamento;
    private javax.swing.JButton consultarHabilidade;
    private javax.swing.JButton consultarInimigo;
    private javax.swing.JButton consultarMissao;
    private javax.swing.JButton consultarPersonagem;
    private javax.swing.JLabel textoEquipamento;
    private javax.swing.JLabel textoHabilidade;
    private javax.swing.JLabel textoInimigo;
    private javax.swing.JLabel textoMissao;
    private javax.swing.JLabel textoPersonagem;
    private javax.swing.JLabel textoPrincipalJogador;
    // End of variables declaration//GEN-END:variables
}
