/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package com.mycompany.projeto_poo2;

/**
 *
 * @author bruno
 */
public class FrameHabilidade extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer FrameHabilidade
     */
    public FrameHabilidade() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtSubtitulo = new javax.swing.JLabel();
        rtTitulo = new javax.swing.JLabel();
        rtNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        rtEfeito = new javax.swing.JLabel();
        cxEfeito = new javax.swing.JTextField();
        rtDescricao = new javax.swing.JLabel();
        cxDescricao = new javax.swing.JTextField();
        btCadHabilidade = new javax.swing.JButton();
        btAltHabilidade = new javax.swing.JButton();
        btConsHabilidade = new javax.swing.JButton();
        btExcHabilidade = new javax.swing.JButton();
        btLimparForm = new javax.swing.JButton();
        btSairForm = new javax.swing.JButton();

        rtSubtitulo.setText("(consultas, alterações e exclusões por nome da habilidade)");

        rtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rtTitulo.setText("Habilidade");

        rtNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtNome.setText("Nome:");

        rtEfeito.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtEfeito.setText("Efeito:");

        rtDescricao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtDescricao.setText("Descrição:");

        btCadHabilidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btCadHabilidade.setText("Cadastrar");
        btCadHabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadHabilidadeActionPerformed(evt);
            }
        });

        btAltHabilidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btAltHabilidade.setText("Alterar");

        btConsHabilidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btConsHabilidade.setText("Consultar");

        btExcHabilidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btExcHabilidade.setText("Excluir");

        btLimparForm.setText("Limpar");

        btSairForm.setText("Sair");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btCadHabilidade)
                                .addGap(18, 18, 18)
                                .addComponent(btAltHabilidade)
                                .addGap(18, 18, 18)
                                .addComponent(btConsHabilidade)
                                .addGap(18, 18, 18)
                                .addComponent(btExcHabilidade)
                                .addGap(39, 39, 39)
                                .addComponent(btLimparForm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSairForm)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rtSubtitulo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(rtTitulo)))
                                .addGap(120, 120, 120))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(rtDescricao)
                                .addGap(18, 18, 18)
                                .addComponent(cxDescricao))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(rtNome)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rtEfeito)
                                        .addGap(22, 22, 22)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cxNome)
                                    .addComponent(cxEfeito))))
                        .addGap(120, 120, 120))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtSubtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtEfeito)
                    .addComponent(cxEfeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtDescricao)
                    .addComponent(cxDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadHabilidade)
                    .addComponent(btAltHabilidade)
                    .addComponent(btConsHabilidade)
                    .addComponent(btExcHabilidade)
                    .addComponent(btLimparForm)
                    .addComponent(btSairForm))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCadHabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadHabilidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadHabilidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltHabilidade;
    private javax.swing.JButton btCadHabilidade;
    private javax.swing.JButton btConsHabilidade;
    private javax.swing.JButton btExcHabilidade;
    private javax.swing.JButton btLimparForm;
    private javax.swing.JButton btSairForm;
    private javax.swing.JTextField cxDescricao;
    private javax.swing.JTextField cxEfeito;
    private javax.swing.JTextField cxNome;
    private javax.swing.JLabel rtDescricao;
    private javax.swing.JLabel rtEfeito;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtSubtitulo;
    private javax.swing.JLabel rtTitulo;
    // End of variables declaration//GEN-END:variables
}
